[package]
name = "TwisteRTanks"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
sfml = "0.16.0"
glu-sys = "0.1.4"
