[package]
name = "TwisteRTanks"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
sfml = "0.16.0"
#sfml = { git = "https://github.com/jeremyletang/rust-sfml"}